INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Agapito del Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Amsic')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Anunas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Balibago')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Capaya')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Claro M. Recto')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Cuayan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Cutcut')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Cutud')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Lourdes North West')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Lourdes Sur')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Lourdes Sur East')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Malabanias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Margot')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Marisol')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Mining')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Pampang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Pandan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Pulung Cacutud')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Pulung Maragul')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Pulungbulu')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Salapungan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sapalibutad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sapangbato')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sta. Teresita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sta. Trinidad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sto. Cristo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sto. Domingo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Tabun')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Angeles City','Virgen Delos Remedios')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Balucuc')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Calantipe')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Cansinala')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Capalangan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Colgante')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Paligui')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Sampaloc')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Sucad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Apalit','Sulipan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Arenas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Baliti')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Batasan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Buensuceso')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Candating')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Cupang (Santa Lucia)')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Gatiawin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Guemasan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Kaledian (Camba)')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','La Paz (Turu)')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Lacmit')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Lacquios')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Mangga-Cacutud')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Mapalad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Matamo (Santa Lucia)')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Panlinlang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Paralaya')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Plazang Luma')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Poblacion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Agustin Norte')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Agustin Sur')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Jose Mesulo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Juan Bano')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Mateo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','San Roque Bitas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Sto. Niño Tabuan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Suclayin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Arayat','Telapayong')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Balas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Cabalantian')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Cabambangan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Cabetican')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Calibutbut')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Concepcion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Dolores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Duat')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Macabacle')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Magliman')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Maliwalu')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Mesalipit')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Parulog')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Potrero')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Sta. Barbara')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Sta. Ines')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Talba')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Bacolor','Tinajero')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Bahay Pare')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Bambang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Barangca')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Barit')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Buas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Cuayang Bugtong')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Dalayap')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Dulong Ilog')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Gulap')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Lanang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Lourdes')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Magumbali')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Mandasig')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Mandili')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Mangga')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Mapaniqui')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Paligui')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Pangclara')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Pansinao')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Paralaya')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Pasig')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Pescadores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Pulong Gubat')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Pulong Palazan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Salapungan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Tagulod')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Talang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Tenejero')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Vizal San Pablo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Vizal Sto. Cristo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Candaba','Vizal Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Anon')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Apalit')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Basa Air Base')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Benedicto')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Bodega')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Cabangcalan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Calantas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Carmencita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Consuelo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Dampe')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Del Carmen')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Fortuna')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Gutad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Mabical')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Maligaya')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Mawacat')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Nabuclod')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Pabanlag')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Paguiruan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Palmayo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Pandaguirig')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Poblacion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Ramon')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Solib')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Floridablanca','Valdez')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Ascomo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Bancal')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Betis')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Jose Abad Santos')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Lambac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Magsaysay')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Maquiapo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Natividad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Plaza Burgos')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Pulungmasle')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Rizal')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Juan Bautista')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Juan Nepomuceno')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Matias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Nicolas 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Nicolas 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Pablo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Rafael')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Solib')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Sta. Filomena')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Sta. Ines')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Sta. Ursula')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Sto. Cristo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Guagua','Valdez')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Balantacan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Bancal Pugad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Bancal Sinubli')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Baruya (San Rafael)')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Calangain')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Concepcion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','De La Paz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Del Carmen')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Don Ignacio Dimson')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Lourdes')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Prado Siongco')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Remedios')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Francisco')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Jose Apunan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Jose Gumi')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Matias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Miguel')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Nicolas 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Nicolas 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Pablo 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Pablo 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Pedro Palcarangan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Pedro Saug')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Roque Arbol')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Roque Dau')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Santiago')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Barbara')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Catalina')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Lucia')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Rita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Teresa 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sta. Teresa 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sto. Cristo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sto. Domingo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Lubao','Sto. Tomas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Atlu-Bola')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Bical')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Bundagul')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Cacutud')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Calumpang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Camachiles')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Dapdap')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Dau')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Dolores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Duquit')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Lakandula')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Mabiga')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Macapagal Village')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Mamatitang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Mangalit')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Marcos Village')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Mawaque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Paralayunan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Poblacion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','San Francisco')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','San Joaquin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Santa Ines')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Santa Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Sapang Balen')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Sapang Biabas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mabalacat','Tabun')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Batasan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Caduang Tete')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Candelaria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Castuli')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Consuelo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Dalayap')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Mataguiti')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Esteban')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Francisco')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Gabriel')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Rafael')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Saplad David')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Sta. Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Sta. Lutgarda')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Sta. Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Sta. Rita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Tacasan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Macabebe','Telacsan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Ayala')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Bucanan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Camias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Dolores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Escaler')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','La Paz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Navaling')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Franciso')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Ildefonso')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Miguel')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Nicolas 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Nicolas 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Pablo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Pedro I')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Pedro II')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Sta. Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Sta. Lucia')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Sta. Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Magalang','Turu')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Alauli')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Bagang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Balibago')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Bebe Anac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Bebe Matua')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Bulacus')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Cambasi')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Malauli')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Nigui')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Palimpe')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Puti')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sagrada (Tibagin)')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','San Isidro Anac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','San Isidro Matua')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sapang Kawayan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sta. Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sta. Lucia Anac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sta. Lucia Matua')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sta. Lucia Paguiba')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sta. Lucia Wakas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Masantol','Sua')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Acli')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Anao')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Balas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Buenavista')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Camuning')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Cawayan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Concepcion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Culubasa')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Divisoria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Dolores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Eden')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Gandus')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Lagundi')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Laput')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Laug')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Masamat')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Masangsang')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Nueva Victoria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Pandacaqui')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Pangatlan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Panipuan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Parian')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Sabanilla')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Carlos')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Jose Malino')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Jose Matulid')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Lorenzo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Miguel')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Pablo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Patricio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Rafael')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Santa Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Santa Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Sapang Maisac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Sto. Cristo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Sto. Domingo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Suclaban')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Mexico','Tangle')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Bulac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Dawe')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Lourdes')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Maniango')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','San Francisco 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','San Francisco 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Saplad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Sta. Catalina')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Sta. Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Sta. Rita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Sto. Domingo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Minalin','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Babo Pangulo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Babo Sacan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Balubad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Calzadang Bayu')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Camias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Cangatba')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Diaz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Dolores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Inararo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Jalung')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Mancatian')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Manibaug Libutad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Manibaug Paralaya')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Manibaug Pasig')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Manuali')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Mitla Proper')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Palat')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Pias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Pio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Planas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Poblacion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Pulong Santol')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Salu')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','San Jose Mitla')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Sapang Uwak')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Sepung Bulaun')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Sinura')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Sta. Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Porac','Villa Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Alasas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Baliti')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Bulaon')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Calulut')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Del Carmen')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Del Pilar')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Del Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Dela Paz Norte')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Dela Paz Sur')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Dolores')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Juliana')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Lara')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Lourdes')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Magliman')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Maimpis')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Malino')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Malpitic')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Pandaras')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Panipuan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Pulung Bulu')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Quebiawan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Saguin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Felipe')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Sindalan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Sta. Lucia')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Sta. Teresita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Fernando','Telabastagan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Carlos')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','San Sebastian')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sta. Catalina')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sta. Cruz Pambilog')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sta. Cruz Poblacion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sta. Lucia')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sta. Rita')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Luis','Sto. Tomas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','Concepcion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','De La Paz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Miguel')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Pablo Libutad')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Pablo Proper')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','Sta. Cruz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','San Simon','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Batang 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Batang 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Mabuanbuan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Malusac')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Sabitanan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','San Antonio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','San Nicolas 1st')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','San Nicolas 2nd')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Sta. Lucia')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sasmuan','Sto. Tomas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Bartolome')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Joaquin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Nicolas')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Pablo')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Pedro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','San Roque')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','Santiago')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','Sta. Lucia')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','Sta. Maria')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Ana','Sto. Rosario')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','Becuran')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','Dila-dila')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Agustin')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Basilio')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Isidro')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Jose')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Juan')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Matias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sta. Rita','Sta. Monica')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','Moras De La Paz')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','Poblacion')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','San Bartolome')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','San Matias')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','San Vicente')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','Sto. Niño')
INSERT INTO Location_Barangays(Province, Town, Barangay) values ('Pampanga','Sto. Tomas','Sto. Rosario')

