// This class was coldly generated by ST4bby on 7/16/2017 4:07:37 PM.
// Read more at http://jbubriski.github.com/ST4bby/
using System;

namespace Database.Tables
{
	
	public partial class AccountTokens
	{
		public long Id { get; set; }
		
		public string Username { get; set; }
		
		public string Token { get; set; }
		
		public DateTime? Expiration { get; set; }
		
		public string WindowsUsername { get; set; }
		
		public string MachineName { get; set; }
		
		public string IpAddress { get; set; }
		
		public DateTime Created { get; set; }
		
		public DateTime Modified { get; set; }
		
		public string CreatedBy { get; set; }
		
		public string ModifiedBy { get; set; }
		public string GetInsertQueryString()
		{
			return @"DECLARE @output table ( Id int, Created Datetime, CreatedBy nvarchar(20), Modified DateTime, ModifiedBy nvarchar(20)); 
					 INSERT INTOs [AccountTokens] ( Username, Token, Expiration, WindowsUsername, MachineName, IpAddress, Created, Modified, CreatedBy, ModifiedBy ) 
					 VALUES (@Username, @Token, @Expiration, @WindowsUsername, @MachineName, @IpAddress, getdate(), getdate(), @CreatedBy, @ModifiedBy) 
					 SELECT * from @output ";
		}
	}
}
