// This class was coldly generated by ST4bby on 7/16/2017 4:07:37 PM.
// Read more at http://jbubriski.github.com/ST4bby/
using System;

namespace Database.Tables
{
	
	public partial class Location_Towns
	{
		public int Id { get; set; }
		
		public int ProvinceId { get; set; }
		
		public string Town { get; set; }
		
		public string ZipCode { get; set; }
		public string GetInsertQueryString()
		{
			return @"DECLARE @output table ( Id int, Created Datetime, CreatedBy nvarchar(20), Modified DateTime, ModifiedBy nvarchar(20)); 
					 INSERT INTOs [Location_Towns] ( ProvinceId, Town, ZipCode ) 
					 VALUES (@ProvinceId, @Town, @ZipCode) 
					 SELECT * from @output ";
		}
	}
}
