// This class was coldly generated by ST4bby on 7/16/2017 4:07:37 PM.
// Read more at http://jbubriski.github.com/ST4bby/
using System;

namespace Database.Tables
{
	
	public partial class Persons
	{
		public int Id { get; set; }
		
		public string Lastname { get; set; }
		
		public string Firstname { get; set; }
		
		public string MiddleName { get; set; }
		
		public string Mi { get; set; }
		
		public string NameExtension { get; set; }
		
		public string Gender { get; set; }
		
		public string BirthDate { get; set; }
		
		public string Street { get; set; }
		
		public string Barangay { get; set; }
		
		public string Town { get; set; }
		
		public string Province { get; set; }
		
		public DateTime Created { get; set; }
		
		public DateTime Modified { get; set; }
		
		public string CreatedBy { get; set; }
		
		public string ModifiedBy { get; set; }
		public string GetInsertQueryString()
		{
			return @"DECLARE @output table ( Id int, Created Datetime, CreatedBy nvarchar(20), Modified DateTime, ModifiedBy nvarchar(20)); 
					 INSERT INTOs [Persons] ( Lastname, Firstname, MiddleName, Mi, NameExtension, Gender, BirthDate, Street, Barangay, Town, Province, Created, Modified, CreatedBy, ModifiedBy ) 
					 VALUES (@Lastname, @Firstname, @MiddleName, @Mi, @NameExtension, @Gender, @BirthDate, @Street, @Barangay, @Town, @Province, getdate(), getdate(), @CreatedBy, @ModifiedBy) 
					 SELECT * from @output ";
		}
	}
}
